export enum ConfigKey {
    DOMAIN_SERVER = 'DOMAIN_SERVER',
    PORT_API = 'PORT_API',
    PORT_WEB = 'PORT_WEB',
    JWT_ACCESS_SECRET = 'JWT_ACCESS_SECRET',
    JWT_REFRESH_SECRET = 'JWT_REFRESH_SECRET'
}
